# Generated by Django 4.2.1 on 2023-05-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='germanword',
            old_name='name',
            new_name='word',
        ),
    ]
