# Generated by Django 4.2.1 on 2023-06-15 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GermanWord',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=200)),
                ('article', models.CharField(max_length=200)),
                ('types', models.CharField(max_length=200)),
                ('translation1', models.CharField(max_length=200)),
                ('translation2', models.CharField(max_length=200)),
                ('translation3', models.CharField(max_length=200)),
                ('sentence1', models.CharField(max_length=200)),
                ('sentence2', models.CharField(max_length=200)),
                ('sentence3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('days_streak', models.IntegerField(default=0)),
                ('words_learned', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('incorrect_attempts', models.IntegerField(default=0)),
                ('average_response_time', models.DurationField(blank=True, null=True)),
                ('longest_streak', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('green_cards', models.ManyToManyField(related_name='game_sessions_green', to='dictApp.germanword')),
                ('red_cards', models.ManyToManyField(related_name='game_sessions_red', to='dictApp.germanword')),
                ('unclassified_cards', models.ManyToManyField(related_name='game_sessions_unc', to='dictApp.germanword')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yellow_cards', models.ManyToManyField(related_name='game_sessions_yellow', to='dictApp.germanword')),
            ],
        ),
    ]
