# Generated by Django 4.2.1 on 2023-06-10 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('days_streak', models.IntegerField(default=0)),
                ('words_learned', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('incorrect_attempts', models.IntegerField(default=0)),
                ('average_response_time', models.DurationField(blank=True, null=True)),
                ('longest_streak', models.IntegerField(default=0)),
                ('green_cards', models.ManyToManyField(related_name='game_sessions_green', to='dictApp.germanword')),
                ('red_cards', models.ManyToManyField(related_name='game_sessions_red', to='dictApp.germanword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yellow_cards', models.ManyToManyField(related_name='game_sessions_yellow', to='dictApp.germanword')),
            ],
        ),
    ]
