# Generated by Django 4.2.1 on 2023-07-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatistics',
            name='average_response_time',
        ),
        migrations.RemoveField(
            model_name='userstatistics',
            name='correct_attempts',
        ),
        migrations.RemoveField(
            model_name='userstatistics',
            name='guess_ratio',
        ),
        migrations.RemoveField(
            model_name='userstatistics',
            name='incorrect_attempts',
        ),
        migrations.RemoveField(
            model_name='userstatistics',
            name='total_attempts',
        ),
        migrations.RemoveField(
            model_name='userstatistics',
            name='words_learned',
        ),
    ]
