# Generated by Django 4.2.1 on 2023-07-17 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0002_remove_userstatistics_average_response_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistics',
            name='last_day_played',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
