# Generated by Django 4.2.1 on 2023-06-13 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictApp', '0002_gamesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='average_response_time',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='correct_attempts',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='days_streak',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='guess_ratio',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='incorrect_attempts',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='longest_streak',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='total_attempts',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='words_learned',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='unclassified_cards',
            field=models.ManyToManyField(related_name='game_sessions_unc', to='dictApp.germanword'),
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('days_streak', models.IntegerField(default=0)),
                ('words_learned', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('incorrect_attempts', models.IntegerField(default=0)),
                ('average_response_time', models.DurationField(blank=True, null=True)),
                ('longest_streak', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
