# Generated by Django 4.2.1 on 2023-06-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0003_remove_gamesession_average_response_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='germanword',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
