# Generated by Django 4.2.1 on 2023-06-13 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictApp', '0004_alter_germanword_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='user',
        ),
        migrations.CreateModel(
            name='User_GameSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamesession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictApp.gamesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
